<?php

namespace App\Database\Seeds\Demo;
use \CodeIgniter\Database\Seeder;
use Faker\Extension\Helper;

class UserSeeder extends \CodeIgniter\Database\Seeder
{
    /**
     * @return mixed|void
     * Run Seeder
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        // Call String Helper
        helper('text');

        // Call Faker
        $faker = \Faker\Factory::create('tr_TR');

        // Make Loop For 100 Demo Data
        for($i = 0; $i < 100; $i++){
            // Make Data
            $data =[
                'group_id' => null,
                'first_name' => $faker->firstName,
                'sur_name' => $faker->lastName,
                'email' => $faker->email,
                'password' => password_hash('my12345',PASSWORD_DEFAULT),
                'phone' => $faker->phoneNumber,
                'verify_key' => random_string('alpha',64),
                'verify_code' => random_int(100000,999999),
                'bio' => $faker->paragraph,
                'status' => USER_ACTIVE
            ];

            // Insert Data
            $this->db->table('users')->insert($data);
        }
    }
}