<?php

namespace App\Database\Seeds;
use \CodeIgniter\Database\Seeder;

class AdminSeeder extends \CodeIgniter\Database\Seeder
{
    /**
     * @return mixed|void
     * Run Seeder
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        // Call String Helper
        helper('text');

        // Make Data
        $data =[
            'group_id' => null,
            'first_name' => 'EMRE',
            'sur_name' => 'KILIÇ',
            'email' => 'emrekilic@mutfakyapim.com',
            'password' => password_hash('my12345',PASSWORD_DEFAULT),
            'phone' => '+905494410120',
            'verify_key' => random_string('alpha',64),
            'verify_code' => random_int(100000,999999),
            'bio' => 'Lorem ipsum',
            'status' => USER_ACTIVE
        ];

        // Insert Data
        $this->db->table('users')->insert($data);
    }
}